services:
  app:
    build:
      context: .
    ports:
      - "5000:5000"
    environment:
      - SPRING_DATASOURCE_URL=process.env.SPRING_DATASOURCE_URL
      - SPRING_DATASOURCE_USERNAME=process.env.SPRING_DATASOURCE_USERNAME
      - SPRING_DATASOURCE_PASSWORD=process.env.SPRING_DATASOURCE_PASSWORD
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=process.env.POSTGRES_USER
      - POSTGRES_PASSWORD=process.env.POSTGRES_PASSWORD
      - POSTGRES_DB=process.env.POSTGRES_DB
    ports:
      - "5432:5432"
