networks:
  dev: 
    driver: bridge

services:
  server:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    networks:
      - dev
    env_file:
      - .env

  postgres:
    image: "postgres"
    ports:
      - "5432:5432"
    networks:
      - dev
    env_file:
      - .env
